# Generated by Django 5.2.9 on 2026-01-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BmiTalaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('faculty', models.CharField(choices=[('Kompyuter_inginiringi', 'Kompyuter_inginiringi'), ('Axborot_texnologiyalar', 'Axborot_texnologiyalar')])),
                ('group_name', models.CharField(max_length=64)),
                ('theme_name', models.TextField()),
                ('years', models.CharField(max_length=32)),
                ('files', models.FileField(upload_to='student_files/')),
            ],
        ),
    ]
