# Generated by Django 5.2.9 on 2026-01-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmitalaba',
            old_name='name',
            new_name='first_name',
        ),
    ]
