# Generated by Django 5.2.9 on 2026-01-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0002_rename_name_bmitalaba_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmitalaba',
            name='total_ball',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
