# Generated by Django 5.2.9 on 2025-12-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PQaror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qaror_num', models.CharField(unique=True)),
                ('title', models.CharField()),
                ('created_at', models.DateTimeField()),
                ('description', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='PQarorlar/')),
            ],
            options={
                'verbose_name': 'Prezident Qarorlari',
            },
        ),
    ]
