# Generated by Django 5.2.9 on 2026-01-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DQaror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qaror_num', models.CharField(unique=True)),
                ('title', models.CharField()),
                ('created_at', models.DateTimeField()),
                ('description', models.CharField()),
                ('file', models.FileField(upload_to='DQarorlar/')),
            ],
            options={
                'verbose_name': 'Direktor Qarorlari',
            },
        ),
        migrations.CreateModel(
            name='HQaror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qaror_num', models.CharField(unique=True)),
                ('title', models.CharField()),
                ('created_at', models.DateTimeField()),
                ('description', models.CharField()),
                ('file', models.FileField(upload_to='HQarorlar/')),
            ],
            options={
                'verbose_name': 'Hokim Qarorlari',
            },
        ),
        migrations.CreateModel(
            name='PQaror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qaror_num', models.CharField(unique=True)),
                ('title', models.CharField()),
                ('created_at', models.DateTimeField()),
                ('description', models.CharField()),
                ('file', models.FileField(upload_to='PQarorlar/')),
            ],
            options={
                'verbose_name': 'Prezident Qarorlari',
            },
        ),
        migrations.CreateModel(
            name='VQaror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qaror_num', models.CharField(unique=True)),
                ('title', models.CharField()),
                ('created_at', models.DateTimeField()),
                ('description', models.CharField()),
                ('file', models.FileField(upload_to='VQarorlar/')),
            ],
            options={
                'verbose_name': 'Vazirlik Qarorlari',
            },
        ),
    ]
