# Generated by Django 5.2.9 on 2025-12-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarorlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqaror',
            name='description',
            field=models.CharField(),
        ),
    ]
