# Generated by Django 5.2.9 on 2026-01-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oqituvchilar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='shartnoma_bekor_raqami',
        ),
        migrations.AddField(
            model_name='teacher',
            name='shartnoma_bekor_sana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='buyruq',
            field=models.FileField(blank=True, null=True, upload_to='buyruqlar/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='ishlagan_bolimi',
            field=models.CharField(choices=[('Axborot xavfsizligi', 'Axborot xavfsizligi'), ('Axborot texnologiyalari', 'Axborot texnologiyalari'), ("Raqamli ta'lim texnologiyalari", "Raqamli ta'lim texnologiyalari"), ('Dasturiy injiniring', 'Dasturiy injiniring'), ('Gumanitar va ijtimoiy fanlar', 'Gumanitar va ijtimoiy fanlar'), ('Kompyuter tizimlari kafedrasi', 'Kompyuter tizimlari kafedrasi'), ('Tabiiy fanlar', 'Tabiiy fanlar'), ('Telekommunikatsiya injiniringi', 'Telekommunikatsiya injiniringi'), ('Tillar kafedrasi', 'Tillar kafedrasi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='ishlagan_lavozimi',
            field=models.CharField(choices=[('Assistent', 'Assistent'), ('Katta o‘qituvchi', 'Katta o‘qituvchi'), ('Dotsent', 'Dotsent'), ('Professor', 'Professor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pasport',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
