# Generated by Django 5.2.9 on 2026-01-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oqituvchilar', '0002_remove_teacher_shartnoma_bekor_raqami_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
