# Generated by Django 5.2.9 on 2026-01-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('qabul_sana', models.DateField()),
                ('chiqish_sana', models.DateField(blank=True, null=True)),
                ('shartnoma_raqami', models.IntegerField(unique=True)),
                ('shartnoma_bekor_sana', models.DateField(blank=True, null=True)),
                ('ishlagan_fakultet', models.CharField(choices=[('Kompyuter inginirinigi', 'Kompyuter inginiringi'), ('Axborot texnologiyalari', 'Axborot texnologiyalari')])),
                ('ishlagan_bolimi', models.CharField(choices=[('Axborot xavfsizligi', 'Axborot xavfsizligi'), ('Axborot texnologiyalari', 'Axborot texnologiyalari'), ("Raqamli ta'lim texnologiyalari", "Raqamli ta'lim texnologiyalari"), ('Dasturiy injiniring', 'Dasturiy injiniring'), ('Gumanitar va ijtimoiy fanlar', 'Gumanitar va ijtimoiy fanlar'), ('Kompyuter tizimlari kafedrasi', 'Kompyuter tizimlari kafedrasi'), ('Tabiiy fanlar', 'Tabiiy fanlar'), ('Telekommunikatsiya injiniringi', 'Telekommunikatsiya injiniringi'), ('Tillar kafedrasi', 'Tillar kafedrasi')], max_length=100)),
                ('pasport', models.CharField(max_length=20, unique=True)),
                ('buyruq', models.FileField(blank=True, null=True, upload_to='professor_buyruqlari/')),
                ('is_active', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
