# Generated by Django 5.2.9 on 2025-12-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('faculty', models.CharField(choices=[('Kompyuter_inginiringi', 'Kompyuter_inginiringi'), ('Axborot_texnologiyalar', 'Axborot_texnologiyalar')])),
                ('group_name', models.CharField(max_length=64)),
                ('theme_name', models.TextField()),
                ('years', models.CharField(max_length=32)),
                ('files', models.FileField(upload_to='student_files/')),
            ],
        ),
    ]
