# Generated by Django 5.2.9 on 2026-01-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Custom', 'Custom')], default='Custom', null=True),
        ),
    ]
